# Custom Language File for Launcher Customizer

[ejs.app]
title = "ZLauncher"

[ejs.landing]
mediaGitHubURL = "https://zlauncher.zergiv2.tech/"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@zergiv2102"
mediaDiscordURL = "https://discord.com/users/377860450294956042"

[ejs.settings]
sourceGithubLink = "https://github.com/Zergiv/ZLauncher"
supportLink = "https://github.com/Zergiv/ZLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenido"
welcomeDescription = "Fork para la comunidad de Zergiv2"
welcomeDescCTA = "Estás a solo unos clicks de entrar."
